### ISSUE TITLE
How are zones dealt with?

### ISSUE THREAD

**Issue by judgej** [JustinHook/royal-mail-price-calculator#1]
I can see this package takes details of the shipment (weight, dimensions) and the service that you wish to send it by. However, I can't see any details about the zones.

The UK is split into four shipping zones, based on county and postcode prefixes. The prices for each of these services will differ, depending on which zone you are sending to. How does this package handle those differing prices?

Thanks.

**Comment by judgej** [comment]
Also looking for a package to give the zone, based on the address (generally the country and the postcode, where the rules are to look at the postcode prefixes) to complete the full picture.

**Comment by JustinHook** [comment]
Do you have a link to a page on the Royal Mail website that mentions the four shipping zones?
I've taken a quick look at their site and can't see any mention.
Their price finder provides a price based on the destination being the UK which they say includes "the Highlands and Islands, Scilly Isles and the Isle of Man."

**Comment by judgej** [comment]
Ha, I thought I did. I was going on data I was given in a ticket for implementing some costings, and it turns out the costing for another courier (UK Mail) was mixed up in that data. So, dhoh, move along please, nothing to see here ;-) It did not occur to me that Royal Mail are not allowed to differentiate between different regions in the UK like this, at least for the time-being until they lobby to government to have that rule dropped.

Sorry about that. I'll close the ticket.
