### ISSUE TITLE
Stable release?

### ISSUE THREAD

**Issue by judgej** [JustinHook/royal-mail-price-calculator#2]
Would you be willing to make a stable release tag for this package? At the moment packagist only has dev-master, which is never recommended on a production site, as there is no control over what changes get pulled in.

Any semver version number would be great, then we can lock usage to major or minor versions as necessary.

Thanks.

**Comment by JustinHook** [comment]
I've just created a 1.0 release.

**Comment by judgej** [comment]
Perfect, thank you :thumbsup:
