### ISSUE TITLE
Can't find class?

### ISSUE THREAD

**Issue by Benspring100** [JustinHook/royal-mail-price-calculator#3]
Fatal error: Class 'RoyalMailPriceCalculator\Calculator' not found in C:\xampp\htdocs\royal-mail-price-calculator-master\index.php on line 8

I used composer and installed all the dependencies in the composer.json file. I get the error above ^

**Comment by JustinHook** [comment]
@Benspring100 `require 'vendor/autoload.php';` was missing from the example code in the readme. Can you test again with the updated code?

**Comment by Benspring100** [comment]
Its already included:

The script as a whole:

`<?php

require_once 'vendor/autoload.php';

use \RoyalMailPriceCalculator\Calculator;
use \RoyalMailPriceCalculator\Package;

$app = new \Slim\Slim();
$app->response->headers->set('Content-Type', 'application/json');
$app->config('debug', false);

$app->error(function (\Exception $e) use ($app) {
    $app->response->setStatus(400);
    echo json_encode(array(
        'message' => $e->getMessage() //This is the problem
    ));
});

$app->get('/', function() use ($app) {

```
$length = $app->request->get('length');
if (empty($length)) {
    throw new \Exception("Missing 'length' parameter.");
}

$width = $app->request->get('width');
if (empty($width)) {
    throw new \Exception("Missing 'width' parameter.");
}

$depth = $app->request->get('depth');
if (empty($depth)) {
    throw new \Exception("Missing 'depth' parameter.");
}

$weight = $app->request->get('weight');
if (empty($depth)) {
    throw new \Exception("Missing 'weight' parameter.");
}

$services = $app->request->get('services');
if (empty($services)) {
    throw new \Exception("Missing 'services' parameter.");
}
$services =  explode(",", $services);

$calculator = new Calculator();

$package = new Package();
$package->setDimensions($length, $width, $depth);
$package->setWeight($weight);

$serviceClasses = array();

$serviceClassMap = array(
    'firstclass' => '\RoyalMailPriceCalculator\Services\FirstClassService',
    'secondclass' => '\RoyalMailPriceCalculator\Services\SecondClassService',
    'signedforfirstclass' => '\RoyalMailPriceCalculator\Services\SignedForFirstClassService',
    'signedforsecondclass' => '\RoyalMailPriceCalculator\Services\SignedForSecondClassService',
    'guaranteedby9am' => '\RoyalMailPriceCalculator\Services\GuaranteedByNineAmService',
    'guaranteedby9amwithsaturday' => '\RoyalMailPriceCalculator\Services\GuaranteedByNineAmWithSaturdayService',
    'guaranteedby1pm' => '\RoyalMailPriceCalculator\Services\GuaranteedByOnePmService',
    'guaranteedby1pmwithsaturday' => '\RoyalMailPriceCalculator\Services\GuaranteedByOnePmWithSaturdayService',
);

foreach ($services as $service) {
    if (isset($serviceClassMap[strtolower($service)])) {
        $serviceClasses[] = new $serviceClassMap[strtolower($service)]();
    } else {
        throw new \Exception("Unknown service '$service'.");
    }
}

if (empty($serviceClasses)) {
    throw new \Exception("No valid services found.");
}

$calculator->setServices($serviceClasses);

//$calculator[0]['service'];
//$calculator[0]['prices']['price'];
//$calculator[0]['prices']['compensation'] ;

echo json_encode($calculator->calculatePrice($package), JSON_PRETTY_PRINT);

//var_dump($calculator->calculatePrice($package));

$arr = $calculator->calculatePrice($package);

/*foreach($arr as $val) {
    echo $val['service']->name.' - ';
    echo $val['prices'][0]['price'].' - ';
    echo $val['prices'][0]['compensation'].' - '; 
} */

foreach($arr as $val) {
if($val['service']->name = "2nd Class") {
    $service1 = $val['service']->name.' || ';
    $price1 =  $val['prices'][0]['price'].' || ';
    $compensation1 = $val['prices'][0]['compensation'].' || '; 
    }
}
```

});

$app->run();
print $service1 . '</ br>';
echo $price1 . '</br>';
echo $compensation1;
`

I managed to fix this by making the classes public and running a FOR loop.

`foreach($arr as $val) {
    if($val['service']->name = "2nd Class") {
        $service1 = $val['service']->name.' || ';
        $price1 =  $val['prices'][0]['price'].' || ';
        $compensation1 = $val['prices'][0]['compensation'].' || '; 
        }
    }`

Feel like its an inefficient way of getting the data in a variable though. Any other ideas? Love the API BTW! :)

**Comment by JustinHook** [comment]
This should do what you want:

``` php
<?php

require 'vendor/autoload.php';

use \RoyalMailPriceCalculator\Calculator;
use \RoyalMailPriceCalculator\Package;
use \RoyalMailPriceCalculator\Services\SecondClassService;

$calculator = new Calculator();

$package = new Package();
$package->setDimensions(15, 15, 0.4);
$package->setWeight(90);

$calculator->setServices(array(new SecondClassService()));

$second_class_service_prices = $calculator->calculatePrice($package)[0];

$service_name = $second_class_service_prices['service']->getName();
$price = $second_class_service_prices['prices'][0]['price'];
$compensation = $second_class_service_prices['prices'][0]['compensation'];

echo "Service: ". $service_name ."\n";
echo "Price: ". $price ."\n";
echo "Compensation: ". $compensation ."\n";
```

Will output:

```
Service: 2nd Class
Price: 0.54
Compensation: 20
```

**Comment by Benspring100** [comment]
Oh wow! After a full 7 hours of searching through all of the code, analyzing it, error reporting this is such a simple fix! Thank you so much aha! :) Woop woop!

**Comment by Benspring100** [comment]
If I was wanting the other Second Class? (The Signed For 2nd Class) how would I output that?

**Comment by Benspring100** [comment]
Say if I wanted to use first class to? all of these variables are for second class. Sorry for all the questions! Really good API!

**Comment by JustinHook** [comment]
It depends on how you want to use them.
Are you trying to provide a list to a user for them to select a service? Or are you trying to do something else?

**Comment by Benspring100** [comment]
That's exactly what I want! I am wanting to show a selection to my user base. Thank you very much!

**Comment by Benspring100** [comment]
If I can show a list of maybe four of five selections of sending items which the user can chose from. I can code everything else, I just need all the variables inside to work with Second Class, First Class etc. If there is a way to change all of the variables to use it with certain services I can do things such as taking the values from the URL ($_GET) etc. :)

**Comment by JustinHook** [comment]
Can you show me the code you have so far for displaying the actual dropdown?

**Comment by Benspring100** [comment]
I havn't really got anything but four input fields with the 'length', 'width', 'depth' and 'weight'.
Which they input as integers in CM and Grams. Then just a drop down with: First Class, Second Class, Signed for first class andsigned for second class. Which is it. Its a very small piece of code and when the user enters in all the information I will use those variables and output it to the user. I was going to eventually use jQuery so it dynamically shows the user the prices. 

Do you want the small code of the 4 input fields and the drop down menu?

**Comment by JustinHook** [comment]
Yeah can you send me over the code you are using to display the form fields.

**Comment by Benspring100** [comment]
`<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

<style>
.margin {
	margin: 40%;
}
</style>

<div class="margin">
	<form method="post" action="index.php">
		<input type="text" class="form-control" name="length" placeholder="Enter Length" id="usr"></br>
		<input type="text" class="form-control" name="width" placeholder="Enter Width" id="usr"></br>
		<input type="text" class="form-control" name="depth" placeholder="Enter Depth" id="usr"></br>
		<input type="text" class="form-control" name="weight" placeholder="Enter Weight" id="usr"></br>

		<select class="form-control" id="sel1" name="service">
		    <option value="firstclass">First Class</option>
		    <option value="secondclass">Second Class</option>
		    <option value="signedfirstclass">Signed First Class</option>
		    <option value="signedsecondclass">Signed Second Class</option>
	  </select></br>

	  <button type="submit" class="btn btn-primary">Submit</button>

	</form>
</div>`

**Comment by Benspring100** [comment]
```
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

<style>
.margin {
    margin: 40%;
}
</style>

<div class="margin">
    <form method="post" action="index.php">
        <input type="text" class="form-control" name="length" placeholder="Enter Length" id="usr"></br>
        <input type="text" class="form-control" name="width" placeholder="Enter Width" id="usr"></br>
        <input type="text" class="form-control" name="depth" placeholder="Enter Depth" id="usr"></br>
        <input type="text" class="form-control" name="weight" placeholder="Enter Weight" id="usr"></br>

        <select class="form-control" id="sel1" name="service">
            <option value="firstclass">First Class</option>
            <option value="secondclass">Second Class</option>
            <option value="signedfirstclass">Signed First Class</option>
            <option value="signedsecondclass">Signed Second Class</option>
      </select></br>

      <button type="submit" class="btn btn-primary">Submit</button>

    </form>
</div>
```

**Comment by Benspring100** [comment]
If you just copy and paste that, its what I have as a base page. Will get all of the information needed from the user to work out the prices.

**Comment by JustinHook** [comment]
This shows how it can be made to work with your form:

``` php
<?php

require 'vendor/autoload.php';

use \RoyalMailPriceCalculator\Calculator;
use \RoyalMailPriceCalculator\Package;
use \RoyalMailPriceCalculator\Services\FirstClassService;
use \RoyalMailPriceCalculator\Services\SecondClassService;
use \RoyalMailPriceCalculator\Services\SignedForFirstClassService;
use \RoyalMailPriceCalculator\Services\SignedForSecondClassService;

$calculator = new Calculator();

$package = new Package();
$package->setDimensions($_POST['length'], $_POST['width'], $_POST['depth']);
$package->setWeight($_POST['weight']);

switch ($_POST['service']) {
    case 'firstclass':
        $service = new FirstClassService();
        break;
    case 'secondclass':
        $service = new SecondClassService();
        break;
    case 'signedfirstclass':
        $service = new SignedForFirstClassService();
        break;
    case 'signedsecondclass':
        $service = new SignedForSecondClassService();
        break;
}


$calculator->setServices(array($service));

$prices = $calculator->calculatePrice($package)[0];

echo "Service: " . $prices['service']->getName() . "<br/>";
echo "Prices:<br/>";
foreach ($prices['prices'] as $price) {
    echo $price['price'] . " - " . $price['compensation'] . "<br/>";
}
```

**Comment by Benspring100** [comment]
Fantastic, thank you so much. Also, in regards to royal mail I've just had a thought. Is compensation the amount I am getting back? Just realized. 

Thank you and I will use this script, very useful!

**Comment by JustinHook** [comment]
Yeah its the maximum compensation for lost or damaged items.

**Comment by Benspring100** [comment]
Brilliant, do you have Twitter or are on any social networks?

**Comment by JustinHook** [comment]
No I don't have a twitter account.
